name: Build CI

on:
  push:
  pull_request:
  release:
    types: [published]
  check_suite:
    types: [rerequested]

jobs:
  uspace-docker:
    strategy:
        matrix:
            imgname:
                - debian:buster
    runs-on: ubuntu-16.04
    container: ${{ matrix.imgname }}
    steps:
    - run: apt-get update && apt-get -y --no-install-recommends install git ca-certificates sudo curl gnupg
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0
    - run: cp share/linuxcnc/linuxcnc.asc /etc/apt/trusted.gpg.d/linuxcnc.asc
    - run: git fetch --tags https://github.com/linuxcnc/linuxcnc
    - name: build in docker
      run: env REALTIME=uspace ./scripts/travis-install-build-deps.sh && ./scripts/travis-build-test.sh
